import "./styles.scss";
import "../src/icon/github.svg";
import "../src/icon/github-blue.svg";
import "../src/icon/instagram.svg";
import "../src/icon/facebook.svg";
import "../src/icon/speech.svg";
import "../src/icon/hero-left.svg";
import "../src/icon/hero-right.svg";
console.log("hello wossrld!");
